### ISSUE TITLE
USER STORY: Project Setup

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#1]
# DESCRIPTION
As a **Developer** I can **set up the Django project structure with necessary dependencies** so that **I can start building e-commerce website**

# TASKS
- [x] Task 1 – Create a new Django project using django-admin
- [x] Task 2 – Configure database settings for PostgreSQL or SQLite
- [x] Task 3 – Set up static files and media file handling
- [x] Task 4 – Initialize Git repository and add initial project files

# ITERATION
[Iteration 0](https://github.com/AmeenNoor/halal-shop/milestone/2)
# EPIC
#28

**Comment by AmeenNoor** [comment]
Tasks completed on commit [558fad0](https://github.com/AmeenNoor/halal-shop/commit/558fad0ac35c2d204e20a776818e0587e144fc0d) & [31307b4](https://github.com/AmeenNoor/halal-shop/commit/31307b472468bb2d039da9bf09cf79f9ac0955f4)
