### ISSUE TITLE
USER STORY: Product Editing

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#10]
# DESCRIPTION
As an **Admin user** I can **edit existing products** so that **I can update product information and maintain accuracy**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am logged in as an admin user
**When**  I navigate to the admin dashboard
**Then** I should see a list of existing products with an option to edit each product
- Criteria 2
**Given** I am editing an existing product
**When** I make changes to the product details and save them
**Then** the product information should be successfully updated in the product catalog

# TASKS
- [x] Task 1 - Implement views and logic for editing existing products
- [x] Task 2 - Create templates for the product editing form
- [x] Task 3 - Set up URL routes for the product editing functionality

# ITERATION
[Iteration 3](https://github.com/AmeenNoor/halal-shop/milestone/5)
# EPIC
#30

**Comment by AmeenNoor** [comment]
Tasks completed on commit [559207b](https://github.com/AmeenNoor/halal-shop/commit/559207bcaa555c64a3863b12e2b46528b4c43e3d), [86bc611](https://github.com/AmeenNoor/halal-shop/commit/86bc611d841ce3eeb96e1d088d68715320dbd751) & [a8450e6](https://github.com/AmeenNoor/halal-shop/commit/a8450e636d371c70dab13f66c190a8b2c26e310c)
