### ISSUE TITLE
USER STORY: Product Removal

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#11]
# DESCRIPTION
As an **Admin User** I can **remove products from the website** so that **I can manage the product catalog and remove outdated or discontinued items**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am logged in as an admin user
**When**  I navigate to the admin dashboard,
**Then** I should see a list of existing products with an option to remove each product
- Criteria 2
**Given** I am removing a product,
**When** I confirm the removal action,
**Then** the product should be successfully removed from the product catalog

# TASKS
- [x] Task 1 - Implement views and logic for removing products
- [x] Task 2 - Design templates for the product removal confirmation prompt
- [x] Task 3 - Set up URL routes for the product removal functionality

# ITERATION
[Iteration 3](https://github.com/AmeenNoor/halal-shop/milestone/5)
# EPIC
#30

**Comment by AmeenNoor** [comment]
Tasks completed on commit [5e6da6a](https://github.com/AmeenNoor/halal-shop/commit/5e6da6a20d22b14b535fe863ddbc327b420e675d), [d2b09fc](https://github.com/AmeenNoor/halal-shop/commit/d2b09fc15e8eb505356cd513ced4ab1574d6a560) & [23587af](https://github.com/AmeenNoor/halal-shop/commit/23587afa23bab248f86f1824f86a7f62001c3409)
