### ISSUE TITLE
USER STORY: Product Browsing

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#12]
# DESCRIPTION
As a **Site Visitor** I can **browse through a variety of products** so that **I can find items that interest me**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am a site visitor
**When**  I visit the website's product page
**Then** I should see a list of products available for browsing
- Criteria 2
**Given** I am browsing products
**When** I navigate through different product categories
**Then** I  should be able to explore products based on my interests

# TASKS
- [x] Task 1 - Implement views and logic for displaying products on the product page
- [x] Task 2 - Design templates for the product listing page
- [x] Task 3 - Set up URL routes for accessing the product page

# ITERATION
[Iteration 1](https://github.com/AmeenNoor/halal-shop/milestone/3)
# EPIC
#31

**Comment by AmeenNoor** [comment]
Tasks completed on commit [77a5b74](https://github.com/AmeenNoor/halal-shop/commit/77a5b742bc1a06f39a89e543e8b944837263cdf5) & [367c81c](https://github.com/AmeenNoor/halal-shop/commit/367c81cabdf3d4ffcde4af26b1555d11f108f87e)
