### ISSUE TITLE
USER STORY: Product Details Viewing

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#13]
# DESCRIPTION
As a **Site Visitor** I can **view detailed information about a product including images and descriptions** so that **I can make an informed purchasing decision**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am a site visitor
**When**  I click on a specific product on the product listing page
**Then** I should be redirected to the product details page
- Criteria 2
**Given** I am viewing a product's details
**When** I view the product image, description, and other relevant information
**Then** I should have access to all necessary details to make an informed purchasing decision.

# TASKS
- [x] Task 1 - Implement views and logic for displaying detailed product information
- [x] Task 2 - Design templates for the product details page
- [x] Task 3 - Set up URL routes for accessing and displaying product details

# ITERATION
[Iteration 1](https://github.com/AmeenNoor/halal-shop/milestone/3)
# EPIC
#31

**Comment by AmeenNoor** [comment]
Tasks completed on commit [bfe3083](https://github.com/AmeenNoor/halal-shop/commit/bfe30830cd3d6f62095dc5119970601cf7b37e70), [8599ec3](https://github.com/AmeenNoor/halal-shop/commit/8599ec36568e0bbbe60c07cb3139532b50200985) & [cae388f](https://github.com/AmeenNoor/halal-shop/commit/cae388f4b44c75be1bb102109c7746646f0a0233)
