### ISSUE TITLE
USER STORY: Product Search

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#14]
# DESCRIPTION
As a **Site Visitor** I can **search for products** so that **I can quickly find specific items of interest**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am a site visitor
**When**  I enter a search query in the search bar
**Then** I should see relevant products matching the search query
- Criteria 2
**Given** I am viewing search results
**When** I click on a product from the search results
**Then** I should be redirected to the product details page for the selected product

# TASKS
- [x] Task 1 - Implement search functionality to query products based on user input
- [x] Task 2 - Design templates for displaying search results
- [x] Task 3 - Set up URL routes for handling search requests

# ITERATION
[Iteration 1](https://github.com/AmeenNoor/halal-shop/milestone/3)
# EPIC
#31

**Comment by AmeenNoor** [comment]
Tasks completed on commit [3a269a3](https://github.com/AmeenNoor/halal-shop/commit/3a269a304cf6a90326fa150c3ddeb4a308a4c882), [298d34d](https://github.com/AmeenNoor/halal-shop/commit/298d34dc20ce72cd51933af49de83021a38e2a69) & [8d68762](https://github.com/AmeenNoor/halal-shop/commit/8d6876284ec0632c9b412057523ecd062d79d7e9)
