### ISSUE TITLE
USER STORY: View Products by Category

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#15]
# DESCRIPTION
As a **Site Visitor** I can **view products by category** so that **I can explore items within specific product categories**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am a site visitor
**When**  I navigate to the product page
**Then** I should see a list of product categories available for browsing
- Criteria 2
**Given** I am viewing product categories
**When** I click on a specific category
**Then** I should be redirected to a page displaying products belonging to the selected category

# TASKS
- [x] Task 1 - Implement views and logic for displaying product categories on the product page
- [x] Task 2 - Design templates for the category listing page
- [x] Task 3 - Set up URL routes for accessing category pages and displaying products by category

# ITERATION
[Iteration 1](https://github.com/AmeenNoor/halal-shop/milestone/3)
# EPIC
#31

**Comment by AmeenNoor** [comment]
Tasks completed on commit [daa799f](https://github.com/AmeenNoor/halal-shop/commit/daa799fc9141a9b45d278c38af48c22a870a5f7d), [6e3abb9](https://github.com/AmeenNoor/halal-shop/commit/6e3abb9888a9bd108a70e0c41bcdc9d5d7e4489b) & [5607bd9](https://github.com/AmeenNoor/halal-shop/commit/5607bd977fda8ed42b2c5580aefaeb46e25247e7)
