### ISSUE TITLE
USER STORY: Filter Products by Criteria

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#16]
# DESCRIPTION
As a **Site Visitor** I can **filter products based on different criteria** so that **I can narrow down my product search**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am a site visitor
**When**  I am viewing a list of products
**Then** I should see options to filter products based on criteria such as price range, alphabetical order, etc.
- Criteria 2
**Given**  I apply a filter
**When** I select a specific filter option
**Then** I should see the product list updated to display products that meet the selected criteria

# TASKS
- [x] Task 1 - Implement filtering functionality to filter products based on user-selected criteria.
- [x] Task 2 - Design templates for displaying filter options and updating the product list accordingly
- [x] Task 3 - Set up URL routes for handling filter requests and updating product listings

# ITERATION
[Iteration 1](https://github.com/AmeenNoor/halal-shop/milestone/3)
# EPIC
#31

**Comment by AmeenNoor** [comment]
Tasks completed on commit [531cd56](https://github.com/AmeenNoor/halal-shop/commit/531cd56101f82105f09556a4032d1c7b613092bf), [d666226](https://github.com/AmeenNoor/halal-shop/commit/d66622624d7b5ae1960944983c7514f392a8ae13) & [23ab0fb](https://github.com/AmeenNoor/halal-shop/commit/23ab0fbb2ceb8302729114b82dfeb7eb977df715)
