### ISSUE TITLE
USER STORY: Add Product to Cart

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#17]
# DESCRIPTION
As a **Site Visitor** I can **add products to my cart** so that **I can keep track of items I intend to purchase**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am a site visitor
**When**  I view the product details page
**Then** I should see an option to add the product to my cart
- Criteria 2
**Given** I click on the "Add to Cart" button
**When** I confirm the action
**Then** the selected product should be added to my cart

# TASKS
- [x] Task 1 - Implement functionality to add products to the cart
- [x] Task 2 - Design templates for displaying the "Add to Cart" button on the product details page
- [x] Task 3 - Set up URL routes for handling cart update requests

# ITERATION
[Iteration 4](https://github.com/AmeenNoor/halal-shop/milestone/6)
# EPIC
#32

**Comment by AmeenNoor** [comment]
Tasks completed on commit [ec531f8](https://github.com/AmeenNoor/halal-shop/commit/ec531f8cfb8e8cb90db19e83d1fd6e3ee7291014) & [873155e](https://github.com/AmeenNoor/halal-shop/commit/873155ecfd65074a29fa7e2294dd789a51060043)
