### ISSUE TITLE
USER STORY: Edit Product in Cart

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#18]
# DESCRIPTION
As a **Site Visitor** I can **edit products in my cart before proceeding to payment** so that **I can customize my order according to my preferences**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am a site visitor with items in my cart
**When**  I navigate to the cart page
**Then** I should see options to edit the products in my cart, such as updating quantities or removing items
- Criteria 2
**Given** I update the quantity or remove an item
**When** I confirm the action
**Then** the cart should be updated accordingly

# TASKS
- [x] Task 1 - Implement functionality to edit products in the cart, including updating quantities and removing items
- [x] Task 2 - Design templates for displaying the cart page with options to edit cart items
- [x] Task 3 - Set up URL routes for handling cart editing requests

# ITERATION
[Iteration 4](https://github.com/AmeenNoor/halal-shop/milestone/6)
# EPIC
#32

**Comment by AmeenNoor** [comment]
Tasks completed on commit [02fa693](https://github.com/AmeenNoor/halal-shop/commit/02fa6932cdda05e85d13b7a35b2feb0a42669015) & [33b8ae9](https://github.com/AmeenNoor/halal-shop/commit/33b8ae915ae4644f0a611ddd58df3a48a0eb3a37)
