### ISSUE TITLE
USER STORY: View Cart Page

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#19]
# DESCRIPTION
As a **Site Visitor** I can **view the contents of my cart** so that **I can review the items I have added before proceeding to checkout**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am a site visitor with items in my cart
**When** I navigate to the cart page
**Then** I should see a list of products currently in my cart along with their details such as name, quantity, and price
- Criteria 2
**Given** I am viewing my cart
**When** I review the items and quantities
**Then** I should have the option to proceed to checkout or continue shopping

# TASKS
- [x] Task 1 - Implement functionality to display the contents of the cart on the cart page
- [x] Task 2 - Design templates for the cart page to show cart items and their details
- [x] Task 3 - Set up URL routes for accessing the cart page

# ITERATION
[Iteration 4](https://github.com/AmeenNoor/halal-shop/milestone/6)
# EPIC
#32

**Comment by AmeenNoor** [comment]
Tasks completed on commit [33b8624](https://github.com/AmeenNoor/halal-shop/commit/33b86245c02983e626bc0b34717f6e49c2cb4776) & [9ca309b](https://github.com/AmeenNoor/halal-shop/commit/9ca309ba84d33c51ee49e0959094051bcc94f104)
