### ISSUE TITLE
USER STORY: AWS S3 Setup

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#2]
# DESCRIPTION
As a **Developer** I can **set up AWS S3 and IAM to host static and media files for the project** so that **I can store and access files**

# TASKS
- [x] Task 1 - Create an AWS S3 bucket for storing static and media files
- [x] Task 2 - Set up IAM roles and permissions to access the S3 bucket securely
- [x] Task 3 - Configure Django settings to use AWS S3 for storing static and media files
- [x] Task 4 - Ensure static and media files are successfully uploaded and accessed from the S3 bucket

# ITERATION
[Iteration 0](https://github.com/AmeenNoor/halal-shop/milestone/2)
# EPIC
#28

**Comment by AmeenNoor** [comment]
Tasks completed on commit [ace636b](https://github.com/AmeenNoor/halal-shop/commit/ace636b996a25d45a75216afa2a27c5e54ea7375)
