### ISSUE TITLE
USER STORY: View Account

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#22]
# DESCRIPTION
As a **Registered User** I can **view my account details** so that **I can review my personal information and account settings**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am a registered user
**When**  I navigate to the account page
**Then** I should see my account details, including personal information
- Criteria 2
**Given** I am viewing my account details
**When** I review the information
**Then** I should be able to see all relevant details associated with my account

# TASKS
- [ ] Task 1 - Implement functionality to retrieve and display the user's account details.
- [ ] Task 2 - Design templates for the account page to show user information
- [ ] Task 3 - Set up URL routes for accessing the account page

# ITERATION
[Iteration 5](https://github.com/AmeenNoor/halal-shop/milestone/7)
# EPIC
#29

**Comment by AmeenNoor** [comment]
Tasks completed on commit [e58eaaf](https://github.com/AmeenNoor/halal-shop/commit/e58eaaffd1161f65cb8961ff6b59b37e8340b01a), [0eca307](https://github.com/AmeenNoor/halal-shop/commit/0eca3074f8dbac443c7fd9d2c9f68daab7bea71e), [f3e3ac1](https://github.com/AmeenNoor/halal-shop/commit/f3e3ac138f1eb58e70fcf8b3e47bfc534db83341) & [be89039](https://github.com/AmeenNoor/halal-shop/commit/be89039db50ddb1486f165a73c2e1dc80211e425)
