### ISSUE TITLE
USER STORY: Payment

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#26]
# DESCRIPTION
As a **Registered User** I can **make payment for my order securely** so that **I can complete the purchase**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I have filled out the checkout form with valid shipping and payment details
**When**  I proceed to make payment
**Then** I should be directed to a secure payment to enter my payment information
- Criteria 2
**Given** I enter my payment information and confirm the payment
**When** the payment is processed successfully
**Then** my order should be finalized, and the payment should be completed

# TASKS
- [x] Task 1 - Implement functionality to integrate with a secure payment for processing payments
- [x] Task 2 - Design templates for displaying the payment form and handling payment processing
- [x] Task 3 - Set up URL routes for handling payment requests and processing payment responses

# ITERATION
[Iteration 4](https://github.com/AmeenNoor/halal-shop/milestone/6)
# EPIC
#32

**Comment by AmeenNoor** [comment]
Tasks completed on commit [5e616df](https://github.com/AmeenNoor/halal-shop/commit/5e616df0b8d781d073cf1a12ac19c7ffc2c5d160) & [f7db65f](https://github.com/AmeenNoor/halal-shop/commit/f7db65f4bd8198ce66dfc072a17702430e53ff44)
