### ISSUE TITLE
USER STORY: Deployment Using Heroku

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#3]
# DESCRIPTION
As a **Developer** I can **deploy the Django application to Heroku for hosting** so that **I can make the application accessible to users online**

# TASKS
- [x] Task 1 - Create a Heroku account and log in to the Heroku Dashboard
- [x] Task 2 - Create a new Heroku app and configure deployment settings
- [x] Task 3 - Set up environment variables for Django settings and sensitive information
- [x] Task 4 - Push the project code to the Heroku Git repository and trigger deployment

# ITERATION
[Iteration 0](https://github.com/AmeenNoor/halal-shop/milestone/2)
# EPIC
#28

**Comment by AmeenNoor** [comment]
Tasks completed on commit [3eeeba7](https://github.com/AmeenNoor/halal-shop/commit/3eeeba753554451df7c926a133e48e6b47360b6c) & [86cc2f5](https://github.com/AmeenNoor/halal-shop/commit/86cc2f533d3cc39644c03b1de0e7f43a91551c9f)
