### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#4]
# DESCRIPTION
As a **Visitor** I can **register for an account** so that **I can access additional features** 

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am a visitor who wants to register for an account
**When** I navigate to the registration page
**Then** I should see a registration form where I can input my email and password
- Criteria 2
**Given** I have completed the registration form with a valid email and password
**When** I submit the registration form
**Then** a confirmation email should be sent to the provided email address
- Criteria 3
**Given** I have received the confirmation email,
**When** I click on the verification link within the email
**Then** my email address should be verified, and my account should be activated.

# TASKS
- [x] Task 1 - Implement views and logic for the registration form
- [x] Task 2 - Create templates for the registration form
- [x] Task 3 - Set up URL routes for the registration functionality

# ITERATION
[Iteration 2](https://github.com/AmeenNoor/halal-shop/milestone/4)
# EPIC
#29

**Comment by AmeenNoor** [comment]
Tasks completed on commit [8cb2445](https://github.com/AmeenNoor/halal-shop/commit/8cb2445168cb9c71d8590efc7bb1c7ffd3298f54) & [46d033f](https://github.com/AmeenNoor/halal-shop/commit/46d033fb4f7fd7cf67bdbcda793b48542e922c04)
