### ISSUE TITLE
USER STORY: Registered User Login

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#5]
# DESCRIPTION
As a **Registered User** I can **log in to my account** so that **I can access personalized content and manage my account**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am a registered user
**When** I navigate to the login page
**Then** I should see a login form where I can input my credentials

# TASKS
- [x] Task 1 - Implement login views and logic to authenticate registered users
- [x] Task 2 - Design templates for the login form and login page
- [x] Task 3 - Set up URL routes for the login functionality

# ITERATION
[Iteration 2](https://github.com/AmeenNoor/halal-shop/milestone/4)
# EPIC
#29

**Comment by AmeenNoor** [comment]
Tasks completed on commit [40cd2b2](https://github.com/AmeenNoor/halal-shop/commit/40cd2b2f4f343ab7d34c5d0b60c6a67d673bd6b5), [a2a22f7](https://github.com/AmeenNoor/halal-shop/commit/a2a22f78ce0fbc450df967c2fc19e985ca63584f) & [958b5dd](https://github.com/AmeenNoor/halal-shop/commit/958b5dd8144b03f1e89c6b20a1c49fea4e8ceeb3)
