### ISSUE TITLE
USER STORY: Registered User Logout

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#6]
# DESCRIPTION
As a **Registered User** I can **log out of my account** so that **I can ensure secure access and protect my privacy**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given**  I am a registered user logged in to my account
**When**  I navigate to the logout option
**Then** I should see a confirmation prompt asking if I want to log out
- Criteria 2
**Given**  I confirm the logout action
**When** I click on the logout button
**Then** I should be logged out of my account and redirected to the home page
- Criteria 3
**Given** I am logged out of my account
**When** I try to access any restricted content or account-related features
**Then** I should be prompted to log in again before accessing them

# TASKS
- [x] Task 1 - Implement logout views and logic to end the user session
- [x] Task 2 - Design templates for the logout link or button
- [x] Task 3 - Ensure proper redirection after successful logout

# ITERATION
[Iteration 2](https://github.com/AmeenNoor/halal-shop/milestone/4)
# EPIC
#29

**Comment by AmeenNoor** [comment]
Tasks completed on commit [ae7cf49](https://github.com/AmeenNoor/halal-shop/commit/ae7cf49cc310c3549e986c6c80d6717be71b433f), [2b6d2ac](https://github.com/AmeenNoor/halal-shop/commit/2b6d2ac78062755a342a0d055748df33db8aee21) & [ed58a45](https://github.com/AmeenNoor/halal-shop/commit/ed58a45579523357cfd37511bab31a6fcc831ccc)
