### ISSUE TITLE
USER STORY: Change Password

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#7]
# DESCRIPTION
As a **Registered User** I can **change my account password** so that **I can maintain account security**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given**  I am a registered user logged in to my account
**When**  I navigate to the account settings page
**Then** I should see an option to change my password
- Criteria 2
**Given**  I choose to change my password
**When** I input my current password and set a new password
**Then** the password change process should be successful, and my login credentials should be updated
- Criteria 3
**Given** I have successfully changed my password
**When** I try to log in again with my new password
**Then** I should be able to access my account using the updated credentials

# TASKS
- [x] Task 1 - Implement views and forms for changing the password
- [x] Task 2 - Design templates for the change password form
- [x] Task 3 - Set up URL routes for the change password functionality

# ITERATION
[Iteration 5](https://github.com/AmeenNoor/halal-shop/milestone/7)
# EPIC
#29

**Comment by AmeenNoor** [comment]
Tasks completed on commit [171be8b](https://github.com/AmeenNoor/halal-shop/commit/171be8b55ba44b9904f5cfa9d604fa48e2f00842) & [40cd2b2](https://github.com/AmeenNoor/halal-shop/commit/40cd2b2f4f343ab7d34c5d0b60c6a67d673bd6b5)
