### ISSUE TITLE
USER STORY: Forgotten Password Recovery

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#8]
# DESCRIPTION
As a **Registered User** I can **recover my account password if forgotten** so that **I can regain access to my account**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am a registered user who has forgotten my password
**When**  I navigate to the password recovery page
**Then** I should see a form where I can input my email address to initiate the password recovery process
- Criteria 2
**Given** I input my registered email address and submit the recovery form
**When** I confirm the action
**Then** an email containing a password reset link should be sent to the provided email address
- Criteria 3
**Given** I receive the password reset email
**When** I click on the password reset link within the email
**Then** I should be directed to a page where I can input a new password
- Criteria 4
**Given** I input a new password and confirm the password reset
**When** I submit the new password
**Then** the password recovery process should be completed successfully, and I should be able to log in with the new password

# TASKS
- [x] Task 1 - Implement views and logic for initiating password recovery
- [x] Task 2 - Design templates for the password recovery form and email template
- [x] Task 3 - Set up URL routes for the password recovery functionality

# ITERATION
[Iteration 5](https://github.com/AmeenNoor/halal-shop/milestone/7)
# EPIC
#29

**Comment by AmeenNoor** [comment]
Tasks completed on commit [1bffa99](https://github.com/AmeenNoor/halal-shop/commit/1bffa999f3efb8ad8aec65ba3d6ef5ad41815b8f) & [40cd2b2](https://github.com/AmeenNoor/halal-shop/commit/40cd2b2f4f343ab7d34c5d0b60c6a67d673bd6b5)
