### ISSUE TITLE
USER STORY: Adding Product

### ISSUE THREAD

**Issue by AmeenNoor** [AmeenNoor/halal-shop#9]
# DESCRIPTION
As an **Admin User** I can **add new products to the website** so that **I can expand the product catalog and offer more options to users**

# ACCEPTANCE CRITERIA

-  Criteria 1
**Given** I am logged in as an admin user
**When** I navigate to the admin dashboard
**Then** I should see an option to add a new product
- Criteria 2
**Given** I am adding a new product
**When** I fill out the product details form and submit it
**Then** the product should be successfully added to the website's product catalog

# TASKS
- [x] Task 1 - Implement views and logic for adding new products.
- [x] Task 2 - Create templates for the product addition form
- [x] Task 3 - Set up URL routes for the product addition functionality

# ITERATION
[Iteration 3](https://github.com/AmeenNoor/halal-shop/milestone/5)
# EPIC
#30

**Comment by AmeenNoor** [comment]
Tasks completed on commit [11a9603](https://github.com/AmeenNoor/halal-shop/commit/11a9603b6c228366ddfedfe435f1d7f50cde23bb), [8fd4b41](https://github.com/AmeenNoor/halal-shop/commit/8fd4b413851e3fb86746a95e9246599c73f3e26d) & [1f73da8](https://github.com/AmeenNoor/halal-shop/commit/1f73da83425f710825a6e1090f7bc7690309be41)
